# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog_app.BlogPost')),
            ],
        ),
    ]
